on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
  
    permissions:
      id-token: write  # enable GitHub OIDC token issuance for this job
    
    steps:
      # Build the package
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.0.0

      - name: Build
        run: dotnet build -c Release
      
      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: contoso-bot # Recommended: use a secret like ${{ secrets.NUGET_USER }} for your nuget.org username (profile name), NOT your email address
    
      # Push the package
      - name: NuGet push
        run: dotnet nuget push "artifacts/package/release/*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
